import streamlit as st

st.title("Summary & Conclusions")

st.write(
    "The modeling results show that only a few variables meaningfully predict injury "
    "severity, and the findings only partially support the original hypothesis.\n\n"
    "The Random Forest model identified **Age** as the most influential feature. "
    "Although age was not statistically significant in the logistic regression, it "
    "helped the Random Forest create effective nonlinear splits, making it appear as "
    "the top predictor. Other variables such as seatbelt use, airbag status, and time "
    "of day had much smaller importance values.\n\n"
    "The logistic regression model showed that ejection status is the strongest and "
    "most statistically significant predictor of severe injury. Both total and partial "
    "ejection have very large positive coefficients, reflecting the extreme forces "
    "involved when occupants are thrown from the vehicle. Although ejection did not "
    "rank highly in the Random Forest feature-importance scores due to its rarity, "
    "the logistic regression confirms that it is one of the most influential factors "
    "in predicting severe injury. Seatbelt non-use is also a strong and statistically "
    "significant predictor, consistent with its role in preventing ejection and "
    "reducing occupant movement during a crash. Airbag deployment is associated with "
    "higher predicted severity as well, reflecting that airbags deploy in more serious "
    "crashes. Age alone does not significantly affect injury severity, "
    "although its coefficient remains positive. Similarly, the Age × Airbag interaction "
    "also retains a positive coefficient but is not statistically significant in this "
    "model, suggesting ejection overshadows subtle age-related differences in injury risk. \n\n"
    "The interaction plots demonstrated how age interacts with crash conditions. "
    "When airbags deploy, the predicted probability of severe injury increases with "
    "age, showing that older occupants are more vulnerable in high-impact crashes. "
    "Seatbelt use kept predicted severity low across all ages.\n\n"
    "The confusion matrix and classification report revealed that the model "
    "performs well on the majority class (No Injury) but struggles with moderate and "
    "severe injury classes. This is due to strong class imbalance and the very small "
    "number of severe cases in the dataset.\n\n"
    "Overall, the results supported the hypothesis, with the strongest effects aligning with "
    "our expectations. Seatbelt non-use is a strong "
    "and statistically significant predictor of severe injury, and ejection emerged as the "
    "strongest predictor in the logistic regression model. Although ejection did not appear "
    "important in the Random Forest due to its rarity, the logistic regression confirms that "
    "it plays a major role in shaping injury outcomes. Time of day also influenced injury "
    "severity, with both off-peak and peak-hour crashes associated with significantly lower "
    "odds of severe injury compared to nighttime crashes. Age and the interaction terms "
    "retained positive coefficients but were not statistically significant, suggesting that "
    "their effects are overshadowed by more dominant predictors such as ejection and "
    "seatbelt non-use. These findings contrast with the Random Forest results, which ranked "
    "Age highest because tree-based models rely on nonlinear thresholds and use Age more "
    "frequently in splits even when its linear effect is weak. Together, the two models "
    "highlight different aspects of the data, with logistic regression emphasizing the "
    "magnitude of rare but severe events like ejection, and the Random Forest emphasizing "
    "more common patterns such as age-related differences in crash outcomes."
    )
